### ISSUE TITLE
Estilo de la página de registro

### ISSUE THREAD

**Issue by cristianperezshiba** [UB-ES-19/F1-Idealista#2]
Usando un framework/css/scss aplicar estilo a la página de registro para que se parezca a [idealista](https://www.idealista.com/nuevo-usuario).

**Comment by kanales** [comment]
**TODO**
- [ ] Descargar los archivos (sin compilar) de bootstrap
- [ ] Editar bootstrap (scss) para que se adapten al tema de idealista.
- [ ] Implementar el workflow para editar el tema.

**Comment by kanales** [comment]
Estilo fijado similar a [idealista.com]( idealista.com)
